# Generated by Django 3.2.8 on 2021-10-10 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20211006_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='members',
        ),
    ]
